# Project information
site_name: 'Webtechnologie'
site_description: 'Onderwijsmateriaal voor de module Webtechnologie, HBO-ICT jaar 1 semester 2'
site_url: 'https://blackboard.hanze.nl/webapps/blackboard/content/listContentEditable.jsp?content_id=_4384730_1&course_id=_341135_1&mode=reset'
use_directory_urls: false

theme:
  name: 'material'
  custom_dir: 'overrides'
  palette:
    primary: 'blue grey'
    accent: 'orange'
  icon:
    logo: 'material/library'
  language: 'nl'
  include_sidebar: false
extra_css:
  - css/extra.css

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: False
      linenums: True
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.def_list
  - markdown.extensions.admonition
  - markdown.extensions.footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - js/imgs.js

nav:

plugins:
  - mknotebooks:
      execute: false