name: deploy-site

# Only run this when the main branch changes
on:
  push:
    branches:
    - main

# The GITHUB_TOKEN needs write access to push to the gh-pages branch
permissions:
  contents: write

# This job installs dependencies, builds the site, and pushes it to `gh-pages`
jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build the site
      run: |
        mkdocs build

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
